#!/bin/bash

# Takes comma delimited data and converts to dokuwiki table format.
# https://www.dokuwiki.org/wiki:syntax

# sample1,value4
# sample2,value5
# sample3,value6

# |sample1|value4|
# |sample2|value5|
# |sample3|value6|

sed 's/,/|/g' $1 | sed 's/^\(.*\)$/|\1|/g'
