#!/bin/sh 

# Print help if no arguments
help="Run in ~/public_html, prints URL."
usage="Usage: $0 <files>"
if [[ $# -eq 0 ]] ; then
    echo -e "\n$help\n$usage\n" 
    exit 0
fi

# Print full path of all arguments
for i in "$@"
do
	# Get the full path
	fullpath=$(cd $(dirname "$i") && pwd)/$(basename "$i")
	# change /home/sdt5z/public_html to http://people.virginia.edu/~sdt5z/ and change // to / if exists
	echo $fullpath | sed 's/\/home\/sdt5z\/public_html/http:\/\/people.virginia.edu\/~sdt5z\//g' | sed 's@//@/@g2'
done
