#!/bin/bash

# A simple python command-line calculator. 

# Examples:

# $ qc 5/3
# 1.66666666667
# $ qc "log(64, 2)"
# 6.0
# $ qc "sin(pi)"
# 1.22464679915e-16

python -c "from __future__ import division;from math import *;print $1"
